config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :projects
  resources :bugs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    return  unless user.manager?
    can :manage, Project
    can :manage, Bug
    return unless user.developer? ||user.manager?||user.qa?
    can :manage, Bug
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :developer, class_name: 'User', foreign_key: 'developer_id'
  belongs_to :project


  # validates :bug_status, inclusion: { in: ['new', 'started', 'complete'] }
  enum bug_status: {brand_NEW: 0, started:1, complete:2}
  enum bug_type: {feature:0, bug:1}
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :manager, class_name: 'User', foreign_key: 'user_id'
  has_many :bugs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  enum user_type: {manager:0, developer:1, qa:2}
  has_many :projects ,dependent: :nullify
  has_many :bugs,dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:user_type, :email, :password,:password_confirmation)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:user_type,:email, :password, :password_confirmation)}
  end

    rescue_from CanCan::AccessDenied do |exception|
      redirect_to root_url, alert: exception.message
    end

end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
    @bugs = Bug.all
  end

  def new
    debugger
    @bug = current_user.bugs.new
  end

  def create
    # debugger
    @bug = current_user.bugs.new(bug_params)
    debugger
    if @bug.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(:second_frame,partial: "bug",locals: {bug: @bug})
        end
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  private

  def bug_params
    params.require(:bug).permit(:title, :user_id,:developer_id,:project_id,:bug_status,:dead_line,:bug_type,:description)
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
    @projects = Project.all
  end

  def new
    debugger
    @project = current_user.projects.new
  end

  def create
    # debugger
    @project = current_user.projects.new(project_params)
    if @project.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(:second_frame,partial: "project",locals: {project: @project})
        end
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  private

   def project_params
    params.require(:project).permit(:name, :user_id)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
  def developer_options
    User.where(user_type: 'developer').pluck(:email, :id)
  end

  def projects
    Project.all.pluck(:name, :id)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/bugs/_bug.html.erb
<%= turbo_frame_tag "bug_#{bug.id}" do %>
  <div class="bug">
    <%= link_to bug.title, bug_path(bug) %>
    <div class="bug__actions">
      <%= button_to "Delete",
                    bug_path(bug),
                    method: :delete,
                    class: "btn btn--light" %>
      <%= link_to "Edit",
                  edit_bug_path(bug),
                  class: "btn btn--light" %>
    </div>
  </div>
<% end %>

app/views/bugs/_form.html.erb
<%= simple_form_for bug, html: { class: "project form" } do |f| %>
  <% if bug.errors.any? %>
    <div class="error-message">
      <%= bug.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <div>
  <%= f.input :title, input_html: { autofocus: true } %>
  </div>

  <div>
    <%= f.label :Description %><br/>
    <%= f.input :description, input_html: { autofocus: true } %>
  </div>

  <div>
    <%= f.label :bug_Status %><br/>
    <%= f.select :bug_status,  Bug.bug_statuses.keys.map { |status| [status.capitalize, status] },remote:true %>
  </div>

  <div>
    <%= f.label :Bug_type %><br/>
    <%= f.select :bug_type,Bug.bug_types.keys.map { |status| [status.capitalize, status] }  ,remote:true %>
  </div>

  <div>

  <%= f.select :developer_id, options_for_select(developer_options),{},remote: true %>
  </div>

  <div>

    <%= f.select :project_id, options_for_select(projects),{},remote: true %>
  </div>
  <%= f.text_field :dead_line, id: "datepicker" %>
  <%= link_to "Cancel", bugs_path, class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/bugs/edit.html.erb
<h1>Bugs#update</h1>
<p>Find me in app/views/bugs/update.html.erb</p>

app/views/bugs/index.html.erb
<main class="container">
  <%= turbo_frame_tag "first_turbo_frame" do %>
    <div class="header">
      <h1>bugs</h1>
      <%= render "form" ,bug: current_user.bugs.new%>
    </div>
  <% end %>

  <%= turbo_frame_tag "second_frame" do %>
    <%= render partial: "bug", collection: @bugs %>
  <% end %>
</main>

app/views/bugs/new.html.erb
<h1>Bugs#new</h1>
<p>Find me in app/views/bugs/new.html.erb</p>

app/views/layouts/app.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTrackingProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTrackingProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for project, html: { class: "project form" } do |f| %>
  <% if project.errors.any? %>
    <div class="error-message">
      <%= project.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= link_to "Cancel", projects_path, class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/projects/_project.html.erb
<%= turbo_frame_tag "project_#{project.id}" do %>
  <div class="project">
    <%= link_to project.name, project_path(project) %>
    <div class="project__actions">
      <%= button_to "Delete",
                    project_path(project),
                    method: :delete,
                    class: "btn btn--light" %>
      <%= link_to "Edit",
                  edit_project_path(project),
                  class: "btn btn--light" %>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<main class="container">
  <%= turbo_frame_tag "first_turbo_frame" do %>
    <div class="header">
      <h1>Projects</h1>
      <%= render "form" ,project: current_user.projects.new%>
    </div>
    <%= render 'bugs/form',bug: current_user.bugs.new %>
  <% end %>

  <%= turbo_frame_tag "second_frame" do %>
  <%= render partial: "project", collection: @projects %>
  <% end %>
</main>

app/views/projects/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to projects"), projects_url %>

  <div class="header">
    <h1>New Project</h1>
  </div>

  <%= turbo_frame_tag "second_frame" do %>
    <%= render "form", project: @project %>
  <% end %>
</main>